### PR TITLE
Fix/multiple salts

### LINKED ISSUE #13: Manage multiple salts : one salt per tag
## Configuration
`JWT_SECURITY_SALT_PER_TAG=adn:76576576,tag1:7557657657` (in that case JWT_SECURITY_SALT isn't used anymore)
Or JWT_SECURITY_SALT_PER_TAG= { "adn" :"76576576", "tag1" : "7557657657" }

## Notes
Can be useful :
https://github.com/auth0/express-jwt/issues/84

### PR DESCRIPTION
**Pull request by freesteph**
Closes #13 . Allows multiple providers to authenticate against the app.

See https://github.com/betagouv/bbb-analytics/commit/46e7b7aa9c77e7f50df8704f96036136c809275c for details.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -14,12 +14,41 @@ const app = express();
...
+  // fallback to the default JWT_SECURITY_SALT if the new variable isn't set up
+  if (!config.tagsAndSalts) {
+    done(null, config.secret);
+    return;
+  }
+
+  const issuer = config
+    .tagsAndSalts
+    .split(",")
+    .map(i => i.split(":"))
```
Comment (jdauphant) [inline src/index.ts:29]: One optimisation could to do the split at launch instead at each api call.
But it could be early optimisation, the test of this version should be prioritized.

File: Dockerfile [hunk 2]
```diff
@@ -1,16 +1,13 @@
...
-RUN npm install -g
+COPY --chown=node . .
 
-USER node
+RUN npm i
 
-EXPOSE 8100
-RUN npm run dev
\ No newline at end of file
+CMD npm run migrate && npm run dev
```
Comment (jdauphant) [inline Dockerfile:13]: We add confusing with actual Dockerfile that is used to dev.
I will be better to have a production ready Dockerfile and a specific docker file for dev (like "Dockerfile.dev") but this comment is not linked to the subjet of this PR and should be the object of an another PR.

File: src/index.ts (hunk 1 above)
Comment (freesteph) [reply src/index.ts:29]: yes that's what I was working on in the meantime but it makes testing harder because it's global state and global state is hard to mock. I'll give it another try and if I can't do it we can just save it for a rainy day.

File: Dockerfile (hunk 2 above)
Comment (freesteph) [reply Dockerfile:13]: happy to take this on in the next PR

**Review by jdauphant — COMMENTED** [review]
I am good with code. I am wanting for a test from @nschont

**Comment by pielonet** [comment]
Hi, this code works for me too ! (tested for Arawa)

**Comment by jdauphant** [comment]
Thanks @freesteph ! :tada:
